routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/master', function(){
//     return view('master');
// });

// Route::get('/', function () {
//     return view('index');
// });

// Route::get('/data-tables', function () {
//     return view('datatables');
// });

// Route::get('/pertanyaan', 'PertanyaanController@index');
// Route::get('/pertanyaan/create', 'PertanyaanController@create');
// Route::post('/pertanyaan', 'PertanyaanController@store');
// Route::get('/pertanyaan/{id}', 'PertanyaanController@show');
// Route::get('/pertanyaan/{id}/edit', 'PertanyaanController@edit');
// Route::put('/pertanyaan/{id}', 'PertanyaanController@update');
// Route::delete('/pertanyaan/{id}', 'PertanyaanController@destroy'); 


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('profile', 'ProfileController')->middleware('auth');
Route::resource('post', 'PostController')->middleware('auth');
Route::resource('comment', 'CommentController')->middleware('auth');
Route::get('/pengaturan','PengaturanController@index')->middleware('auth');
Route::get('/about', 'AboutController@index')->middleware('auth');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/about.blade.php
@extends('master')

@push('style')
    
@endpush

@section('content')

    {{-- Menampilkan postingan  --}}
    <div class="container-fluid tags">
        <div class="row mt-3 mr-0">
            <div class="col-md-12">
                <div class="card card-primary">
                  <div class="card-header">
                    Tentang Kami
                  </div>  
                  <div class="card-body">
                    <div class="row">
                      <div class="col-md-4">
                        Nama aplikasi
                      </div>
                      <div class="col-md-8">
                        TweeThee
                      </div>
                    </div>
                    <div class="row mt-2">
                      <div class="col-md-4">
                        Framework
                      </div>
                      <div class="col-md-8">
                        <p>Laravel versi 6.*</p>
                      </div>
                    </div>
                    <div class="row mt-2">
                      <div class="col-md-4">
                        Template
                      </div>
                      <div class="col-md-8">
                        <p>AdminLTE-3.0.5</p>
                      </div>
                    </div>
                    <div class="row mt-2">
                      <div class="col-md-4">
                        Repository
                      </div>
                      <div class="col-md-8">
                        https://gitlab.com/arbu24/sosmed.git
                      </div>
                    </div>
                    <div class="row mt-2">
                      <div class="col-md-4">
                        Fungsionalitas aplikasi
                      </div>
                      <div class="col-md-8">
                        <ul>
                          <li>Autentikasi</li>
                          <li>Posting</li>
                          <li>Komentar</li>
                          <li>Pengaturan Profil</li>
                        </ul>
                      </div>
                    </div>
                    <div class="row mt-2">
                      <div class="col-md-4">
                        Deskripsi
                      </div>
                      <div class="col-md-8">
                        <p>Website ini merupakan tugas akhir dari pelatihan yang diadakan oleh Sanbercode. <br> Bootcamp Laravel Batch 22.</p> 
                      </div>
                    </div>
                    <div class="row mt-2">
                      <div class="col-md-4">
                        Kelompok 12
                      </div>
                      <div class="col-md-8">
                        <p>Anggota 1 : Arif Budiman</p>
                        <p>Anggota 2 : Joko Satriyo</p>
                        <p>Anggota 3 : Andy Rachman</p> 
                      </div>
                    </div>
                  </div>
                    <!-- /.card-body -->
                </div>
                <div class="card card-primary">
                  <div class="card-header">
                    Skema ERD
                  </div>  
                  <div class="card-body">
                    <div class="row">
                      <img src="{{asset('img/ERD/erd-sosmed.png')}}" width="90%" alt="skema-erd">
                    </div>
                  </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
    {{-- akhir : menampilkan postingan --}}

@endsection

@push('script')

@endpush

resources/views/home.blade.php
@extends('master')

@push('style')
    
@endpush

@section('home_active')
    active
@endsection

@section('content')

    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
              <div class="col-sm-12">
              {{-- <h1>Home </h1> --}}
              <a class="btn btn-primary btn-lg btn-block" href="{{route('post.create')}}">TweeT</a>
              </div>
          </div>
        </div>
    </section>

    {{-- Menampilkan postingan  --}}
    <section>
      <div class="container-fluid mt-2">
        @if(session('success'))
            <div class="alert alert-success">
              {{session('success')}}
            </div>
        @endif
        <div class="row">
          @forelse ($data as $d)
          <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                  <div class="row">
                    <div class="col-md-9">
                      <div class="user-panel mt-1 pb-1 mb-1 d-flex">
                        <div class="image">
                            <img src="{{asset('assets-adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
                        </div>
                        <div class="info">
                            <a href="#" class="d-block">{{ $d->user->name }}</a>
                            <p> {{$d->created_at}} </p>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-3 d-flex flex-row-reverse">
                      @if ($d->user->id == Auth::id())
                        
                        <form action="{{route('post.destroy',['post'=>$d->id])}}" method="POST" style="display: inline-block">
                          @csrf
                          @method('DELETE')  
                          <a href="{{route('post.edit',[$post = $d->id])}}" type="button" class="btn btn-warning btn-sm"><i class="far fa-edit"></i></a>
                          <input type="submit" name="delete" id="delete" value=" x " class="btn btn-danger btn-sm">
                        </form>
                      @endif
                      <div class="mr-1" style="display: inline-block">
                        <a href="{{route('post.show',['post'=> $d->id])}}" type="button" class="btn btn-info btn-sm"><i class="far fas fa-eye"></i></a>
                      </div>                       
                    </div>
                  </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <center><img src="{{ asset('img/'. $d->image) }}" width="max-width" height="350px"></center>
                  <hr>
                  <p class=" mt-1">{!!$d->isi!!}</p>
                </div>
                <div class="card-footer">
                  <a href="" type="button" class="btn btn-primary btn-sm"><i class="fas fa-thumbs-up"></i></a>
                  <a href="" type="button" class="btn btn-primary btn-sm">comment <i class="far fa-comment"></i></a>
              </div>
            </div>
          </div>
          @empty
              <div class="col-md-12">
            <div class="card">
                <!-- /.card-header -->
                <div class="card-body">
                  <p> Belum ada Postingan</p>
                </div>
            </div>
          </div>
          
          @endforelse
            
        </div>
      </div>
    </section>
    {{-- akhir : menampilkan postingan --}}

@endsection

@push('script')

@endpush

resources/views/index.blade.php
@extends('master')

@push('style')
    
@endpush

@section('home_active')
    active
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Home</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                {{-- <li class="breadcrumb-item active">Beranda</li> --}}
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
      <!-- Main content -->
      <section class="content">
  
        <!-- Default box -->
        <div class="card">
          <div class="card-body">
            <table class="table table-bordered">
                <thead>                  
                  <tr>
                    <th style="width: 10px">#</th>
                    <th>Task</th>
                    <th>Progress</th>
                    <th style="width: 40px">Label</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>1.</td>
                    <td>Update software</td>
                    <td>
                      <div class="progress progress-xs">
                        <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                      </div>
                    </td>
                    <td><span class="badge bg-danger">55%</span></td>
                  </tr>
                  <tr>
                    <td>2.</td>
                    <td>Clean database</td>
                    <td>
                      <div class="progress progress-xs">
                        <div class="progress-bar bg-warning" style="width: 70%"></div>
                      </div>
                    </td>
                    <td><span class="badge bg-warning">70%</span></td>
                  </tr>
                  <tr>
                    <td>3.</td>
                    <td>Cron job running</td>
                    <td>
                      <div class="progress progress-xs progress-striped active">
                        <div class="progress-bar bg-primary" style="width: 30%"></div>
                      </div>
                    </td>
                    <td><span class="badge bg-primary">30%</span></td>
                  </tr>
                  <tr>
                    <td>4.</td>
                    <td>Fix and squish bugs</td>
                    <td>
                      <div class="progress progress-xs progress-striped active">
                        <div class="progress-bar bg-success" style="width: 90%"></div>
                      </div>
                    </td>
                    <td><span class="badge bg-success">90%</span></td>
                  </tr>
                </tbody>
              </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
  
      </section>
      <!-- /.content -->    
@endsection

@push('script')
    
@endpush

resources/views/master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>TweeThee</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('assets-adminlte/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('assets-adminlte/dist/css/adminlte.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  {{-- <link rel="stylesheet" href="{{asset('assets-adminlte/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css')}}"> --}}

  @stack('style')

</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  
  @include('inc.navbar')
  <!-- /.navbar -->

  
  <!-- Main Sidebar Container -->
  @include('inc.main_sidebar')
  

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-8" style="">
        @yield('content')
      </div>
      <div class="col-md-4">
        @include('inc.right_bar')
      </div>
    </div>
    
  </div>
  <!-- /.content-wrapper -->

  {{-- @include('inc.footer') --}}

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{asset('assets-adminlte/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('assets-adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('assets-adminlte/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('assets-adminlte/dist/js/demo.js')}}"></script>

{{-- <script src="{{asset('assets-adminlte/plugins/sweetalert2/sweetalert2.min.js')}}"></script> --}}

@include('sweetalert::alert')

@stack('script')

</body>
</html>

resources/views/pengaturan.blade.php
@extends('master')

@push('style')
    
@endpush

@section('pengaturan_active')
    active
@endsection

@section('content')

    {{-- Menampilkan postingan  --}}
    <div class="container-fluid tags">
        <div class="row mt-3 mr-0">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                      <div class="text-center">
                        <img class="profile-user-img img-fluid img-circle"
                             src="{{asset('assets-adminlte/dist/img/user2-160x160.jpg')}}"
                             alt="User profile picture">
                      </div>
      
                      <h3 class="profile-username text-center">{{Auth::user()->name}}</h3>
      
                      <p class="text-muted text-center">{{Auth::user()->email}}</p>
      
                      <ul class="list-group list-group-unbordered mb-3">
                        <li class="list-group-item">
                            <b>Bergabung Sejak</b> <a class="float-right">{{Auth::user()->created_at}}</a>
                          </li>
                        <li class="list-group-item">
                          <b>Followers</b> <a class="float-right"></a>
                        </li>
                      </ul>
      
                      <a href="{{route('profile.create')}}" class="btn btn-primary btn-block"><b>Tambahkan Deskripsi</b></a>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
    {{-- akhir : menampilkan postingan --}}

@endsection

@push('script')

@endpush