routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/master', function(){
//     return view('master');
// });

// Route::get('/', function () {
//     return view('index');
// });

// Route::get('/data-tables', function () {
//     return view('datatables');
// });

// Route::get('/pertanyaan', 'PertanyaanController@index');
// Route::get('/pertanyaan/create', 'PertanyaanController@create');
// Route::post('/pertanyaan', 'PertanyaanController@store');
// Route::get('/pertanyaan/{id}', 'PertanyaanController@show');
// Route::get('/pertanyaan/{id}/edit', 'PertanyaanController@edit');
// Route::put('/pertanyaan/{id}', 'PertanyaanController@update');
// Route::delete('/pertanyaan/{id}', 'PertanyaanController@destroy'); 


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('profile', 'ProfileController')->middleware('auth');
Route::resource('post', 'PostController')->middleware('auth');
Route::resource('comment', 'CommentController')->middleware('auth');
Route::get('/pengaturan','PengaturanController@index')->middleware('auth');
Route::get('/about', 'AboutController@index')->middleware('auth');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/inc/footer.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.5
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

resources/views/inc/main_sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{asset('assets-adminlte/index3.html')}}" class="brand-link">
      <img src="{{asset('assets-adminlte/dist/img/AdminLTELogo.png')}}"
           alt="AdminLTE Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">TweeThee</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{asset('assets-adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{{route('profile.index')}}" class="d-block">{{ Auth::user()->name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

          <li class="nav-header">Navigation</li>
          <li class="nav-item">
            <a href="/home" class="nav-link @yield('home_active')" >
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Home
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('post.index')}}" class="nav-link @yield('post_active')" >
              <i class="nav-icon fas fa-book"></i>
              <p>
                Postingan Anda
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="/pengaturan" class="nav-link @yield('pengaturan_active')" >
              <i class="nav-icon fas fa-cog"></i>
              <p>
                Pengaturan Akun
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('profile.index')}}" class="nav-link @yield('profile_active')" >
              <i class="nav-icon fas fa-user-circle"></i>
              <p>
                Profile
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/inc/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      {{-- <li class="nav-item d-none d-sm-inline-block">
        <a href="assets-adminlte/index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact </a>
      </li> --}}
    </ul>

    <!-- SEARCH FORM -->
    {{-- <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form> --}}

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      {{-- <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="assets-adminlte/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="assets-adminlte/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('assets-adminlte/dist/img/user3-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li> --}}
      <form action="{{ route('logout') }}" method="POST"">
        @csrf
        <a class="btn btn-outline-info btn-sm" href="/about"><i class="far fa-surprise"></i> Feeling Lucky!</a>
        <a class="btn btn-success btn-sm" href="/pengaturan"><i class="fas fa-cog"></i></a>
        <button class="btn btn-danger btn-sm" type="submit"><i class="fas fa-door-open"></i> Logout</button>
      </form>
    </ul>
  </nav>

resources/views/inc/right_bar.blade.php
{{-- <section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        
    </div>
    </div><!-- /.container-fluid -->
</section> --}}

<div class="container-fluid tags">
    <div class="row mt-3 mr-2">
        <div class="col-md-12">
            <div class="card bg-light">
                <div class="card-header">
                  <h3 class="card-title"><i class="fas fa-tags"></i> Tags</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <a class="btn btn-primary btn-sm mb-2" href="#">Sambercode</a>
                    <a class="btn btn-primary btn-sm mb-2" href="#">Coding</a>
                    <a class="btn btn-primary btn-sm mb-2" href="#">Laravel</a>
                    <a class="btn btn-primary btn-sm mb-2" href="#">Bootstrap</a>
                    <a class="btn btn-primary btn-sm mb-2" href="#">AdminLTE</a>

                </div>
            </div>
        </div>
    </div>
    <div class="row mr-2">
        <div class="col-md-12">
            <div class="card bg-light">
                <div class="card-header">
                  <h3 class="card-title"><i class="fas fa-users"></i> Mungkin anda kenal?</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="user-panel mt-0 pb-0 mb-0">
                        <div class="row">
                            <div class="col-md-4">   
                                <div class="info">
                                    <img src="{{asset('assets-adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
                                    <a href="#">Joko</a> 
                                    {{-- <a href="{{route('profile.show',['profile'=>$user->id])}}">{{$user->name}}</a> --}}
                                </div>
                            </div>
                            <div class="col-md-8">
                                <a class="btn btn-outline-primary btn-sm" href="#">Follow</a>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="user-panel mt-0 pb-0 mb-0">
                        <div class="row">
                            <div class="col-md-4">   
                                <div class="info">
                                    <img src="{{asset('assets-adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
                                    <a href="#">Andy</a> 
                                    {{-- <a href="{{route('profile.show',['profile'=>$user->id])}}">{{$user->name}}</a> --}}
                                </div>
                            </div>
                            <div class="col-md-8">
                                <a class="btn btn-outline-primary btn-sm" href="#">Follow</a>
                            </div>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>